### ISSUE TITLE
error while coverting udp to hls

### ISSUE THREAD

**Issue by gauravv5** [futzu/x9k3#15]
est_scte/seg56.ts:   start: 1572.740000   end: 1578.740000   duration: 6.000000
deleting test_scte/seg51.ts
test_scte/seg57.ts:   start: 1578.740000   end: 1584.740000   duration: 6.000000
deleting test_scte/seg52.ts
test_scte/seg58.ts:   start: 1584.740000   end: 1590.740000   duration: 6.000000
deleting test_scte/seg53.ts
test_scte/seg59.ts:   start: 1590.740000   end: 1596.740000   duration: 6.000000
deleting test_scte/seg54.ts
test_scte/seg60.ts:   start: 1596.740000   end: 1602.740000   duration: 6.000000
deleting test_scte/seg55.ts
test_scte/seg61.ts:   start: 1602.740000   end: 1608.740000   duration: 6.000000
deleting test_scte/seg56.ts
test_scte/seg62.ts:   start: 1608.740000   end: 1614.740000   duration: 6.000000
deleting test_scte/seg57.ts
Traceback (most recent call last):
  File "/usr/local/bin/x9k3", line 5, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/x9k3.py", line 821, in cli
    stuff.run()
  File "/usr/local/lib/python3.6/site-packages/x9k3.py", line 383, in run
    self.decode()
  File "/usr/local/lib/python3.6/site-packages/x9k3.py", line 358, in decode
    super().decode()
  File "/usr/local/lib/python3.6/site-packages/threefive/stream.py", line 225, in decode
    cue = self._parse(pkt)
  File "/usr/local/lib/python3.6/site-packages/x9k3.py", line 335, in _parse
    super()._parse(pkt)
  File "/usr/local/lib/python3.6/site-packages/threefive/stream.py", line 454, in _parse
    self._parse_pts(pkt, pid)
  File "/usr/local/lib/python3.6/site-packages/threefive/stream.py", line 402, in _parse_pts
    if self._pts_flag(payload):
  File "/usr/local/lib/python3.6/site-packages/threefive/stream.py", line 345, in _pts_flag
    return pay[7] & 0x80
IndexError: index out of range
[root@localhost ~]#

**Comment by futzu** [comment]
I commented a line out testing something, I forgot to put it back. Sorry about that.
Upgrade to 2.3.97  and it should be fixed. Let me know how it goes.

```js
python3 -mpip install --upgrade threefive
```

**Comment by futzu** [comment]
Did that fix it?

**Comment by futzu** [comment]
tap tap... you cool?

**Comment by futzu** [comment]
Closing the issue since you aren't talking to me.
